repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args:
          [
            '--max-line-length=88',
            '--ignore=E203,E501,W503',
            '--per-file-ignores=__init__.py:F401',
          ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.5.4
    hooks:
      - id: isort
        exclude: tests/
        args:
          [
            '--line-width',
            '88',
            '--multi-line',
            '3',
            '--trailing-comma',
            '--use-parentheses',
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        exclude: tests/
        additional_dependencies:
          [
            'fastapi==0.61.1',
            'motor==2.3.0',
            'uvicorn==0.12.1',
            'passlib==1.7.3',
            'orjson==3.4.0',
            'aiohttp==3.6.2',
            'typer==0.3.2',
            'requests==2.24.0',
            'pydantic==1.6.1',
          ]
