repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Format Code

  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: Sort Api Imports
        files: '^api/.*\.py'
        args: ['--settings-file', 'api/pyproject.toml']
      - id: isort
        name: Sort Ingester Imports
        files: '^ingester/.*\.py'
        args: ['--settings-file', 'ingester/pyproject.toml']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: Lint Api
        files: '^api/.*\.py'
        args: ['--config', 'api/.flake8']
      - id: flake8
        name: Lint Ingester
        files: '^ingester/.*\.py'
        args: ['--config', 'ingester/.flake8']

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        name: Lint For Security
        exclude: tests/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
        name: Type Check Api
        files: '^api/.*\.py'
        args: ['--config-file', 'api/mypy.ini']
        additional_dependencies:
          [
            'motor==2.3.0',
            'uvicorn==0.13.3',
            'fastapi==0.63.0',
            'orjson==3.4.0',
          ]
      - id: mypy
        name: Type Check Ingester
        files: '^ingester/.*\.py'
        args: ['--config-file', 'ingester/mypy.ini']
        additional_dependencies:
          ['aiohttp==3.6.2', 'typer==0.3.2', 'aiofiles==0.6.0']
