services:
  traefik:
    image: traefik:v2.3
    environment:
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
    depends_on:
      - ingester
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
  ingester:
    build: ./ingester
    init: true
    command: initial
    depends_on:
      - db
    volumes:
      - ./data:/data
  db:
    image: mongo:4.4
    restart: always
  api:
    build: ./api
    init: true
    depends_on:
      - ingester
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.routers.api.rule=HostSNI(`*`)'
    restart: always
