services:
  traefik:
    image: traefik:v2.3
    environment:
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
      - TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME=https
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
    depends_on:
      - ingester
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  ingester:
    build: ./ingester
    init: true
    command: initial
    depends_on:
      - db
  db:
    image: mongo:4.4
    init: true
  api:
    build: ./api
    init: true
    depends_on:
      - ingester
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.entrypoints=websecure'
