services:
  traefik:
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_TLSCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER=https://acme-staging-v02.api.letsencrypt.org/directory
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=""
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE=/letsencrypt/acme.json
    volumes:
      - letsencrypt:/letsencrypt
  api:
    labels:
      - 'traefik.http.routers.api.rule=Host(`api.political-dashboard.com`)'
      - 'traefik.http.routers.whoami.tls.certresolver=letsencrypt'
volumes:
  letsencrypt:
