version: '3.8'
services:
  receiver:
    build: ./receiver
    init: true
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    # restart: always
  db:
    image: mongo:4.2.6
    logging:
      driver: none
    # restart: always
  api:
    build: ./api
    init: true
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - receiver
      - db
    ports:
      - '8000:8000'
    # restart: always
