version: '3.8'
services:
  ingester:
    build: ./ingester
    init: true
    command: ['initial']
    depends_on:
      - db
    # restart: always
  db:
    image: mongo:4.4
    init: true
    logging:
      driver: none
    # restart: always
  api:
    build: ./api
    init: true
    environment:
      PDA_DEV_CONFIG: 1
    depends_on:
      - ingester
      - db
    ports:
      - '8000:8000'
    # restart: always
