version: '3'
services:
  receiver:
    build: ./receiver
    depends_on:
      - db
    restart: always
  db:
    image: mongo:4.2.6
    restart: always
  api:
    build: ./api
    depends_on:
      - db
    restart: always
